### ISSUE TITLE
Example Request: RCON handling

### ISSUE THREAD

**Issue by Lorenz94B** [code34/armago_x64#3]
Hi code34,
would you be so kind to provide a code example of an extensions able to connect to rcon locally to the server and to get replies from it in game? What I have in mind is something like:
onPlayerConnected EH triggers the extension, providing UID to it, the extension finds that UID from the player list and sends its IP back to the game.

I'm a real newbie in C and extensions seems not a so easy "first step" to do in this coding language. Sorry if bothering you with a so specific request, you seem to be the perfect confident person to ask to!

**Comment by FairyTale5571** [comment]
That maybe help https://github.com/multiplay/go-battleye
I made a 50% dll based on Go and will release soon on my github

**Comment by code34** [comment]
Hello Lorenz94B,

i dont know enough RCON to give you a real good answer.

But for your use case, it simpliest to build a little extension that retrieve the ip adress, and send back it through publicvariable internal command.

All depends of what you will do with ip adress. Does those informations will be computed by arma server or other external target ?

**Comment by Lorenz94B** [comment]
Hello code34,
I would like to collect it on a database, using iniDBI or extDB3. The query to the database is not a problem "arma wise", the problem is my lack of knowledge in networking! I have no idea on how to retrieve the ip address.

**Comment by code34** [comment]
in golang, it's very simple.

you have example here:
https://gist.github.com/jniltinho/9787946

**Comment by code34** [comment]
but in fact it's not a real good idea to retrieve the ip adress from dll extension. The ip adress will be local to the client network (..)

So the best way is to retrieve it from server effictvely, i don't know if RCON permits to retrieve thoses informations.

**Comment by code34** [comment]
you also have another solution (..)

you can build an extension that will ask to a distant http server to register an ip adress + uid through a web page. The extension will only send the UID to a webpage, and the webpage will register the ip + uid.

**Comment by Lorenz94B** [comment]
> but in fact it's not a real good idea to retrieve the ip adress from dll extension. The ip adress will be local to the client network (..)
> 
> So the best way is to retrieve it from server effictvely, i don't know if RCON permits to retrieve thoses informations.

The outuput of the RCON command "players" lists ip:port guid and nickname, so data is there, just too noob to work this out myself!

> you also have another solution (..)
> 
> you can build an extension that will ask to a distant http server to register an ip adress + uid through a web page. The extension will only send the UID to a webpage, and the webpage will register the ip + uid.

this seems to complicate the whole thing, to me the best logic solution would be to keep things local to the dedicated server and work as much as possible from there.

Anyway, thank you for the time you're taking to reply!

**Comment by Lorenz94B** [comment]
> That maybe help https://github.com/multiplay/go-battleye
> I made a 50% dll based on Go and will release soon on my github

Thank you FairyTale5571, this still be advanced to me

**Comment by code34** [comment]
yes so the best way is to use a soft like FairyTale5571 client on server side :)

@FairyTale5571 does your client retrive those kind of informations ?

**Comment by FairyTale5571** [comment]
So far, it only works on the record.
The problem is that the rсon cannot be accessed selectively; it will return the entire list of players, which can affect performance. In fact, rcon is not very stable and can break the server, but I will try to find a solution

**Comment by FairyTale5571** [comment]
Hm, about directly ip, I can add it to my returnHWID.dll in next month, but it only for x64

**Comment by Lorenz94B** [comment]
x64 would be enough to the majority of users I think! I really would like to help.. I think the best way to help not working on the code will be to donate!

**Comment by FairyTale5571** [comment]
This is not necessary) Its for free

**Comment by FairyTale5571** [comment]
> in golang, it's very simple.
> 
> you have example here:
> https://gist.github.com/jniltinho/9787946

It returned only local ip's

**Comment by code34** [comment]
>> The problem is that the rсon cannot be accessed selectively; it will return the entire list of players, which can affect performance. In fact, rcon is not very stable and can break the server,database.

is it relative to your code, or rcon go library ?

**Comment by FairyTale5571** [comment]
> > > The problem is that the rсon cannot be accessed selectively; it will return the entire list of players, which can affect performance. In fact, rcon is not very stable and can break the server,database.
> 
> is it relative to your code, or rcon go library ?

github.com/multiplay/go-battleye

**Comment by code34** [comment]
i mean does it relative to the go code, or the rcon on arma server side ?

**Comment by code34** [comment]
no more activity concerning this post, that is not relative to the armago extension itself. if you need more informations concerning dev, you can contact me on bis forum or email
