### ISSUE TITLE
怎么去掉导出的函数名称后面的@n？？

### ISSUE THREAD

**Issue by dzwvip** [code34/armago_x64#5]
怎么去掉导出的函数名称后面的@n ，又可以让win32的客户端 使用 stdcall 方式调用 dll？？

**Comment by code34** [comment]
why do you want to do this ? Arma 32bits uses the mangle names

**Comment by dzwvip** [comment]
I want to compile a 32-bit dll with golang, call VB or delphi, golang default compiled dll does not support - stdcall call mode, the dll generated by your template can be used, but do not want to generate the dll name suffix @xx , compiling with the go build --kill-at command will report an error, so I don't know what to do.

**Comment by code34** [comment]
you can compile the 64 bits c code with the 32bits command (only keep the code inside #ifdef WIN64 section)

It will remove the mangle names.

**Comment by dzwvip** [comment]
Compiled into a 64-bit dll, can not be called by the 32-bit client in the -stdcall mode, I want to compile to a 32-bit dll, and specify - stdcall export mode, but do not want to have the suffix @xx

**Comment by code34** [comment]
normaly you just have to remove the underscore "_" before the name of you function, to turn it off

**Comment by dzwvip** [comment]
ok.
1: gobuild  -buildmode=c-archive 
2: gcc --kill-at .......
