### ISSUE TITLE
Extension works in 32-bit mode, but not in 64-bit

### ISSUE THREAD

**Issue by Reidond** [code34/armago_x64#7]
Hi, i don't know what the heck is happening, but after compiling with instructions i managed to run it in only in 32-bit

[Arma 3 RPT.zip](https://github.com/code34/armago_x64/files/6314253/Arma.3.RPT.zip)

Extension sources
[curly_spoon.zip](https://github.com/code34/armago_x64/files/6314255/curly_spoon.zip)

**Comment by code34** [comment]
64bits version only works if you use the 64bits plateform in arma parameters. It should be the default plateform.

**Comment by code34** [comment]
indeed, something seems to have changed for 64bits, but I don't know where it comes from. Is it a bug in Arma, an evolution in golang, or in TDD, I don't know but I don't have time to look for it. More informations if you want to check the decorated function name at this place: https://docs.microsoft.com/en-us/cpp/build/reference/decorated-names?view=msvc-160

**Comment by Reidond** [comment]
Thank you for clarifying 👍

**Comment by code34** [comment]
@Reidond just fix the 64bits version, it was an export problem certainly relative to tdm-gcc evolution.

**Comment by Reidond** [comment]
now everything works, thank you
