### ISSUE TITLE
Linux example

### ISSUE THREAD

**Issue by Jarvvski** [code34/armago_x64#8]
Do you have an example of creating an extension for linux A3 servers?  I understand that it's `.so` rather than `.dll`s

**Comment by code34** [comment]
go build -o armago_x64.so -buildmode=c-shared .

**Comment by Jarvvski** [comment]
I tried that, but I get build errors when just using a clone of your repo.

**Comment by code34** [comment]
certainly due to your tdcc or golang installation, i just test, it works as expected.

**Comment by Jarvvski** [comment]
I'm assuming I don't need tddcc while building from Linux for just Linux though, right?

I also read the wiki post https://community.bistudio.com/wiki/Extensions

And it's a different code example for using gcc rather than visual. So I imagine I need to use `__attribute` instead?

I have an example repo here - https://github.com/7Cav/a3-fone-home

**Comment by code34** [comment]
yes, you can try to replace the dllexport, and give me a feedback

**Comment by code34** [comment]
any feedback about this ?
